version: '3.1'
services:
    postgres:
        build: ../../apps/postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_DB: $POSTGRES_DB
        volumes: 
            - db-data:/var/lib/postgresql/data
        ports: 
            - "5432:5432"
    rest_api:
        build: ../../apps/rest-api
        #depends_on:
        #    - mysql_auth
        environment: 
            - DB_USERNAME=$POSTGRES_USER
            - DB_PASSWORD=$POSTGRES_PASSWORD
        ports: 
            - "8080:8080"

volumes: 
    db-data:
        driver: local