version: '3.1'
services:
    postgres:
        build: ../../docker-images/postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_DB: $POSTGRES_DB
        volumes: 
            - db-data:/var/lib/postgresql/data
        ports: 
            - "5432:5432"

volumes: 
    db-data:
        driver: local